/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as RegisterMedicoRouteImport } from './routes/register-medico'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContratoRouteImport } from './routes/contrato'
import { Route as MedicoRouteImport } from './routes/_medico'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as MedicoMedicoIndexRouteImport } from './routes/_medico.medico.index'
import { Route as AppGestaoCursosIndexRouteImport } from './routes/_app.gestao-cursos.index'
import { Route as AppCatalogoIndexRouteImport } from './routes/_app.catalogo.index'
import { Route as AppBlogIndexRouteImport } from './routes/_app.blog.index'
import { Route as AppBannersIndexRouteImport } from './routes/_app.banners.index'
import { Route as MedicoMedicoPendenteRouteImport } from './routes/_medico.medico.pendente'
import { Route as MedicoMedicoPedidosRouteImport } from './routes/_medico.medico.pedidos'
import { Route as AppGestaoCursosIdRouteImport } from './routes/_app.gestao-cursos.$id'
import { Route as AppCatalogoNovoRouteImport } from './routes/_app.catalogo.novo'
import { Route as AppCatalogoIdRouteImport } from './routes/_app.catalogo.$id'
import { Route as AppBlogNovoRouteImport } from './routes/_app.blog.novo'
import { Route as AppBlogIdRouteImport } from './routes/_app.blog.$id'
import { Route as MedicoMedicoLojaIndexRouteImport } from './routes/_medico.medico.loja.index'
import { Route as MedicoMedicoCursosIndexRouteImport } from './routes/_medico.medico.cursos.index'
import { Route as MedicoMedicoBlogIndexRouteImport } from './routes/_medico.medico.blog.index'
import { Route as MedicoMedicoCursosIdRouteImport } from './routes/_medico.medico.cursos.$id'
import { Route as MedicoMedicoBlogIdRouteImport } from './routes/_medico.medico.blog.$id'

const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMedicoRoute = RegisterMedicoRouteImport.update({
  id: '/register-medico',
  path: '/register-medico',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoRoute = ContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoRoute = MedicoRouteImport.update({
  id: '/_medico',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const MedicoMedicoIndexRoute = MedicoMedicoIndexRouteImport.update({
  id: '/medico/',
  path: '/medico/',
  getParentRoute: () => MedicoRoute,
} as any)
const AppGestaoCursosIndexRoute = AppGestaoCursosIndexRouteImport.update({
  id: '/gestao-cursos/',
  path: '/gestao-cursos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoIndexRoute = AppCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRoute,
} as any)
const AppBannersIndexRoute = AppBannersIndexRouteImport.update({
  id: '/banners/',
  path: '/banners/',
  getParentRoute: () => AppRoute,
} as any)
const MedicoMedicoPendenteRoute = MedicoMedicoPendenteRouteImport.update({
  id: '/medico/pendente',
  path: '/medico/pendente',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoMedicoPedidosRoute = MedicoMedicoPedidosRouteImport.update({
  id: '/medico/pedidos',
  path: '/medico/pedidos',
  getParentRoute: () => MedicoRoute,
} as any)
const AppGestaoCursosIdRoute = AppGestaoCursosIdRouteImport.update({
  id: '/gestao-cursos/$id',
  path: '/gestao-cursos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoNovoRoute = AppCatalogoNovoRouteImport.update({
  id: '/catalogo/novo',
  path: '/catalogo/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoIdRoute = AppCatalogoIdRouteImport.update({
  id: '/catalogo/$id',
  path: '/catalogo/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogNovoRoute = AppBlogNovoRouteImport.update({
  id: '/blog/novo',
  path: '/blog/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogIdRoute = AppBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AppRoute,
} as any)
const MedicoMedicoLojaIndexRoute = MedicoMedicoLojaIndexRouteImport.update({
  id: '/medico/loja/',
  path: '/medico/loja/',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoMedicoCursosIndexRoute = MedicoMedicoCursosIndexRouteImport.update({
  id: '/medico/cursos/',
  path: '/medico/cursos/',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoMedicoBlogIndexRoute = MedicoMedicoBlogIndexRouteImport.update({
  id: '/medico/blog/',
  path: '/medico/blog/',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoMedicoCursosIdRoute = MedicoMedicoCursosIdRouteImport.update({
  id: '/medico/cursos/$id',
  path: '/medico/cursos/$id',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoMedicoBlogIdRoute = MedicoMedicoBlogIdRouteImport.update({
  id: '/medico/blog/$id',
  path: '/medico/blog/$id',
  getParentRoute: () => MedicoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contrato': typeof ContratoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/register-medico': typeof RegisterMedicoRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/contatos': typeof AppContatosRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/blog/$id': typeof AppBlogIdRoute
  '/blog/novo': typeof AppBlogNovoRoute
  '/catalogo/$id': typeof AppCatalogoIdRoute
  '/catalogo/novo': typeof AppCatalogoNovoRoute
  '/gestao-cursos/$id': typeof AppGestaoCursosIdRoute
  '/medico/pedidos': typeof MedicoMedicoPedidosRoute
  '/medico/pendente': typeof MedicoMedicoPendenteRoute
  '/banners/': typeof AppBannersIndexRoute
  '/blog/': typeof AppBlogIndexRoute
  '/catalogo/': typeof AppCatalogoIndexRoute
  '/gestao-cursos/': typeof AppGestaoCursosIndexRoute
  '/medico/': typeof MedicoMedicoIndexRoute
  '/medico/blog/$id': typeof MedicoMedicoBlogIdRoute
  '/medico/cursos/$id': typeof MedicoMedicoCursosIdRoute
  '/medico/blog/': typeof MedicoMedicoBlogIndexRoute
  '/medico/cursos/': typeof MedicoMedicoCursosIndexRoute
  '/medico/loja/': typeof MedicoMedicoLojaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contrato': typeof ContratoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/register-medico': typeof RegisterMedicoRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/contatos': typeof AppContatosRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/blog/$id': typeof AppBlogIdRoute
  '/blog/novo': typeof AppBlogNovoRoute
  '/catalogo/$id': typeof AppCatalogoIdRoute
  '/catalogo/novo': typeof AppCatalogoNovoRoute
  '/gestao-cursos/$id': typeof AppGestaoCursosIdRoute
  '/medico/pedidos': typeof MedicoMedicoPedidosRoute
  '/medico/pendente': typeof MedicoMedicoPendenteRoute
  '/banners': typeof AppBannersIndexRoute
  '/blog': typeof AppBlogIndexRoute
  '/catalogo': typeof AppCatalogoIndexRoute
  '/gestao-cursos': typeof AppGestaoCursosIndexRoute
  '/medico': typeof MedicoMedicoIndexRoute
  '/medico/blog/$id': typeof MedicoMedicoBlogIdRoute
  '/medico/cursos/$id': typeof MedicoMedicoCursosIdRoute
  '/medico/blog': typeof MedicoMedicoBlogIndexRoute
  '/medico/cursos': typeof MedicoMedicoCursosIndexRoute
  '/medico/loja': typeof MedicoMedicoLojaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_medico': typeof MedicoRouteWithChildren
  '/contrato': typeof ContratoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/register-medico': typeof RegisterMedicoRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/_app/blog/$id': typeof AppBlogIdRoute
  '/_app/blog/novo': typeof AppBlogNovoRoute
  '/_app/catalogo/$id': typeof AppCatalogoIdRoute
  '/_app/catalogo/novo': typeof AppCatalogoNovoRoute
  '/_app/gestao-cursos/$id': typeof AppGestaoCursosIdRoute
  '/_medico/medico/pedidos': typeof MedicoMedicoPedidosRoute
  '/_medico/medico/pendente': typeof MedicoMedicoPendenteRoute
  '/_app/banners/': typeof AppBannersIndexRoute
  '/_app/blog/': typeof AppBlogIndexRoute
  '/_app/catalogo/': typeof AppCatalogoIndexRoute
  '/_app/gestao-cursos/': typeof AppGestaoCursosIndexRoute
  '/_medico/medico/': typeof MedicoMedicoIndexRoute
  '/_medico/medico/blog/$id': typeof MedicoMedicoBlogIdRoute
  '/_medico/medico/cursos/$id': typeof MedicoMedicoCursosIdRoute
  '/_medico/medico/blog/': typeof MedicoMedicoBlogIndexRoute
  '/_medico/medico/cursos/': typeof MedicoMedicoCursosIndexRoute
  '/_medico/medico/loja/': typeof MedicoMedicoLojaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contrato'
    | '/forgot-password'
    | '/login'
    | '/redefinir-senha'
    | '/register'
    | '/register-medico'
    | '/verificar-email'
    | '/contatos'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/notifications'
    | '/profile'
    | '/cursos/$slug'
    | '/blog/$id'
    | '/blog/novo'
    | '/catalogo/$id'
    | '/catalogo/novo'
    | '/gestao-cursos/$id'
    | '/medico/pedidos'
    | '/medico/pendente'
    | '/banners/'
    | '/blog/'
    | '/catalogo/'
    | '/gestao-cursos/'
    | '/medico/'
    | '/medico/blog/$id'
    | '/medico/cursos/$id'
    | '/medico/blog/'
    | '/medico/cursos/'
    | '/medico/loja/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contrato'
    | '/forgot-password'
    | '/login'
    | '/redefinir-senha'
    | '/register'
    | '/register-medico'
    | '/verificar-email'
    | '/contatos'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/notifications'
    | '/profile'
    | '/cursos/$slug'
    | '/blog/$id'
    | '/blog/novo'
    | '/catalogo/$id'
    | '/catalogo/novo'
    | '/gestao-cursos/$id'
    | '/medico/pedidos'
    | '/medico/pendente'
    | '/banners'
    | '/blog'
    | '/catalogo'
    | '/gestao-cursos'
    | '/medico'
    | '/medico/blog/$id'
    | '/medico/cursos/$id'
    | '/medico/blog'
    | '/medico/cursos'
    | '/medico/loja'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_medico'
    | '/contrato'
    | '/forgot-password'
    | '/login'
    | '/redefinir-senha'
    | '/register'
    | '/register-medico'
    | '/verificar-email'
    | '/_app/contatos'
    | '/_app/contratos'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/notifications'
    | '/_app/profile'
    | '/cursos/$slug'
    | '/_app/blog/$id'
    | '/_app/blog/novo'
    | '/_app/catalogo/$id'
    | '/_app/catalogo/novo'
    | '/_app/gestao-cursos/$id'
    | '/_medico/medico/pedidos'
    | '/_medico/medico/pendente'
    | '/_app/banners/'
    | '/_app/blog/'
    | '/_app/catalogo/'
    | '/_app/gestao-cursos/'
    | '/_medico/medico/'
    | '/_medico/medico/blog/$id'
    | '/_medico/medico/cursos/$id'
    | '/_medico/medico/blog/'
    | '/_medico/medico/cursos/'
    | '/_medico/medico/loja/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MedicoRoute: typeof MedicoRouteWithChildren
  ContratoRoute: typeof ContratoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegisterRoute: typeof RegisterRoute
  RegisterMedicoRoute: typeof RegisterMedicoRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  CursosSlugRoute: typeof CursosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-medico': {
      id: '/register-medico'
      path: '/register-medico'
      fullPath: '/register-medico'
      preLoaderRoute: typeof RegisterMedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato': {
      id: '/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof ContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_medico': {
      id: '/_medico'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_medico/medico/': {
      id: '/_medico/medico/'
      path: '/medico'
      fullPath: '/medico/'
      preLoaderRoute: typeof MedicoMedicoIndexRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_app/gestao-cursos/': {
      id: '/_app/gestao-cursos/'
      path: '/gestao-cursos'
      fullPath: '/gestao-cursos/'
      preLoaderRoute: typeof AppGestaoCursosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/': {
      id: '/_app/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof AppCatalogoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog/': {
      id: '/_app/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banners/': {
      id: '/_app/banners/'
      path: '/banners'
      fullPath: '/banners/'
      preLoaderRoute: typeof AppBannersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_medico/medico/pendente': {
      id: '/_medico/medico/pendente'
      path: '/medico/pendente'
      fullPath: '/medico/pendente'
      preLoaderRoute: typeof MedicoMedicoPendenteRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_medico/medico/pedidos': {
      id: '/_medico/medico/pedidos'
      path: '/medico/pedidos'
      fullPath: '/medico/pedidos'
      preLoaderRoute: typeof MedicoMedicoPedidosRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_app/gestao-cursos/$id': {
      id: '/_app/gestao-cursos/$id'
      path: '/gestao-cursos/$id'
      fullPath: '/gestao-cursos/$id'
      preLoaderRoute: typeof AppGestaoCursosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/novo': {
      id: '/_app/catalogo/novo'
      path: '/catalogo/novo'
      fullPath: '/catalogo/novo'
      preLoaderRoute: typeof AppCatalogoNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/$id': {
      id: '/_app/catalogo/$id'
      path: '/catalogo/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof AppCatalogoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog/novo': {
      id: '/_app/blog/novo'
      path: '/blog/novo'
      fullPath: '/blog/novo'
      preLoaderRoute: typeof AppBlogNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog/$id': {
      id: '/_app/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof AppBlogIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_medico/medico/loja/': {
      id: '/_medico/medico/loja/'
      path: '/medico/loja'
      fullPath: '/medico/loja/'
      preLoaderRoute: typeof MedicoMedicoLojaIndexRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_medico/medico/cursos/': {
      id: '/_medico/medico/cursos/'
      path: '/medico/cursos'
      fullPath: '/medico/cursos/'
      preLoaderRoute: typeof MedicoMedicoCursosIndexRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_medico/medico/blog/': {
      id: '/_medico/medico/blog/'
      path: '/medico/blog'
      fullPath: '/medico/blog/'
      preLoaderRoute: typeof MedicoMedicoBlogIndexRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_medico/medico/cursos/$id': {
      id: '/_medico/medico/cursos/$id'
      path: '/medico/cursos/$id'
      fullPath: '/medico/cursos/$id'
      preLoaderRoute: typeof MedicoMedicoCursosIdRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/_medico/medico/blog/$id': {
      id: '/_medico/medico/blog/$id'
      path: '/medico/blog/$id'
      fullPath: '/medico/blog/$id'
      preLoaderRoute: typeof MedicoMedicoBlogIdRouteImport
      parentRoute: typeof MedicoRoute
    }
  }
}

interface AppRouteChildren {
  AppContatosRoute: typeof AppContatosRoute
  AppContratosRoute: typeof AppContratosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppBlogIdRoute: typeof AppBlogIdRoute
  AppBlogNovoRoute: typeof AppBlogNovoRoute
  AppCatalogoIdRoute: typeof AppCatalogoIdRoute
  AppCatalogoNovoRoute: typeof AppCatalogoNovoRoute
  AppGestaoCursosIdRoute: typeof AppGestaoCursosIdRoute
  AppBannersIndexRoute: typeof AppBannersIndexRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
  AppCatalogoIndexRoute: typeof AppCatalogoIndexRoute
  AppGestaoCursosIndexRoute: typeof AppGestaoCursosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContatosRoute: AppContatosRoute,
  AppContratosRoute: AppContratosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppBlogIdRoute: AppBlogIdRoute,
  AppBlogNovoRoute: AppBlogNovoRoute,
  AppCatalogoIdRoute: AppCatalogoIdRoute,
  AppCatalogoNovoRoute: AppCatalogoNovoRoute,
  AppGestaoCursosIdRoute: AppGestaoCursosIdRoute,
  AppBannersIndexRoute: AppBannersIndexRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
  AppCatalogoIndexRoute: AppCatalogoIndexRoute,
  AppGestaoCursosIndexRoute: AppGestaoCursosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MedicoRouteChildren {
  MedicoMedicoPedidosRoute: typeof MedicoMedicoPedidosRoute
  MedicoMedicoPendenteRoute: typeof MedicoMedicoPendenteRoute
  MedicoMedicoIndexRoute: typeof MedicoMedicoIndexRoute
  MedicoMedicoBlogIdRoute: typeof MedicoMedicoBlogIdRoute
  MedicoMedicoCursosIdRoute: typeof MedicoMedicoCursosIdRoute
  MedicoMedicoBlogIndexRoute: typeof MedicoMedicoBlogIndexRoute
  MedicoMedicoCursosIndexRoute: typeof MedicoMedicoCursosIndexRoute
  MedicoMedicoLojaIndexRoute: typeof MedicoMedicoLojaIndexRoute
}

const MedicoRouteChildren: MedicoRouteChildren = {
  MedicoMedicoPedidosRoute: MedicoMedicoPedidosRoute,
  MedicoMedicoPendenteRoute: MedicoMedicoPendenteRoute,
  MedicoMedicoIndexRoute: MedicoMedicoIndexRoute,
  MedicoMedicoBlogIdRoute: MedicoMedicoBlogIdRoute,
  MedicoMedicoCursosIdRoute: MedicoMedicoCursosIdRoute,
  MedicoMedicoBlogIndexRoute: MedicoMedicoBlogIndexRoute,
  MedicoMedicoCursosIndexRoute: MedicoMedicoCursosIndexRoute,
  MedicoMedicoLojaIndexRoute: MedicoMedicoLojaIndexRoute,
}

const MedicoRouteWithChildren =
  MedicoRoute._addFileChildren(MedicoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MedicoRoute: MedicoRouteWithChildren,
  ContratoRoute: ContratoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegisterRoute: RegisterRoute,
  RegisterMedicoRoute: RegisterMedicoRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  CursosSlugRoute: CursosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
